# Generated by Django 5.1.2 on 2024-11-26 20:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minute', models.PositiveSmallIntegerField()),
                ('action', models.CharField(choices=[('goal', 'GOAL'), ('yellow_card', 'YELLOW CARD'), ('red_card', 'RED CARD'), ('sub', 'SUB')], max_length=15)),
                ('major_event_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='team.match')),
                ('minor_event_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.player')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
