# Generated by Django 5.1.2 on 2024-12-01 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_matchevent'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='team.match')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice', models.CharField(choices=[('home_win', 'HOME_WIN'), ('away_win', 'AWAY_WIN'), ('draw', 'DRAW')], max_length=8)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='team.poll')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='user.userprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('poll', 'profile'), name='poll_unique_profile')],
            },
        ),
    ]
