# Generated by Django 5.1.2 on 2024-12-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_poll_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.FileField(null=True, upload_to='team_logo'),
        ),
    ]
