# Generated by Django 5.1.2 on 2024-12-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.URLField(null=True),
        ),
    ]
