# Generated by Django 5.1.2 on 2024-12-03 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_team_logo'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_open', models.BooleanField(default=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='team.match')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscussionMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='team.discussion')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_messages', to='user.userprofile')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
